version: '3.8'

services:
  db:
    image: postgres:14.10
    restart: always
    container_name: postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

  pgadmin:
    build: ./pgadmin
    container_name: pgadmin
    env_file: .env
    ports:
      - "80:80"
    user: root
    entrypoint: /bin/sh -c "sed -i -e 's/POSTGRES_USER/'${POSTGRES_USER}'/g' /pgadmin4/servers.json; sed -i -e 's/POSTGRES_PASSWORD/'${POSTGRES_PASSWORD}'/g' /pgadmin4/servers.json; /entrypoint.sh;"
    depends_on:
      - db

  web:
    build: .
    container_name: django
    entrypoint: ./pong/django-entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
