# Generated by Django 4.2.9 on 2024-06-04 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0004_statistic_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_score', models.IntegerField()),
                ('player2_score', models.IntegerField()),
                ('date_played', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Game History',
                'verbose_name_plural': 'Game Histories',
            },
        ),
        migrations.RemoveField(
            model_name='statistic',
            name='player',
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name': 'Custom User', 'verbose_name_plural': 'Custom Users'},
        ),
        migrations.AddField(
            model_name='customuser',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='total_games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='winner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='game_history',
            field=models.ManyToManyField(blank=True, related_name='players', to='pong.gamehistory'),
        ),
    ]
