# Generated by Django 4.2.9 on 2024-06-04 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0005_gamehistory_remove_statistic_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(default='avatar/ponguser.png', upload_to='avatar/'),
        ),
    ]
