# Generated by Django 4.2.9 on 2024-06-05 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0006_remove_gamehistory_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamehistory',
            name='winner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='won_games', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
