# Generated by Django 4.2.9 on 2024-06-04 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0007_message_blockeduser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=2000)),
            ],
        ),
        migrations.RenameField(
            model_name='blockeduser',
            old_name='timestamp',
            new_name='blocked_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='blocked_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blockeduser',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blocker', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='value',
            field=models.CharField(default=1, max_length=1000000),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='blockeduser',
            unique_together={('user', 'blocked_user')},
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocked',
        ),
        migrations.RemoveField(
            model_name='blockeduser',
            name='blocker',
        ),
    ]
