# Generated by Django 4.2.9 on 2024-06-05 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pong', '0008_alter_gamehistory_winner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamehistory',
            name='winner',
        ),
        migrations.AddField(
            model_name='gamehistory',
            name='player1_won',
            field=models.BooleanField(default=False),
        ),
    ]
